dist: trusty

language: node_js

node_js:
  - "14.5.0"

before_install:

install:
  - rm -rf node_modules/ # remove any remaining artifacts from a previous build
  - npm i
  - rm -rf build/ # remove any remaining artifacts from a previous build
  - npx hardhat --version
  - npx hardhat clean

jobs:
  include:
      - stage: compile
        name: "Compile contracts"
        script: npm run compile

      - stage: tests
        name: "Unit tests"
        script: npm run test

      - stage: tests
        name: "Solidity Lint"
        script: npm run lint:sol

      - stage: tests
        name: "JS Lint"
        script: npm run lint

      - stage: coverage
        name: "Solidity Test Coverage"
        if: branch = develop
        script: npm run coveralls
